#define CHECK_IRONSIGHTS 1
#define CHECK_SCOPE 2
#define CHECK_STOCK 3
#define CHECK_BARREL 4
#define CHECK_UNDER 5

#define ATTACH_IRONSIGHTS 1
#define ATTACH_SCOPE 2
#define ATTACH_STOCK 3
#define ATTACH_BARREL 4
#define ATTACH_UNDER 5
