/obj/structure/closet/secure_closet/ru_soldier
	name = "russian soldat equipment"
	req_access = list(access_ru_soldier)

	New()
		..()
		new /obj/item/weapon/shovel/spade/russia(src)
		new /obj/item/clothing/under/ru_uniform(src)
		new /obj/item/clothing/shoes/jackboots(src)
		new /obj/item/clothing/head/helmet/tactical/ru(src)
		new /obj/item/clothing/suit/storage/vest/heavy/ru(src)
		new /obj/item/weapon/gun/projectile/automatic/akm(src)
		new /obj/item/weapon/storage/belt/security(src)
		for(var/i = 0; i < 8; i++)
			new /obj/item/ammo_magazine/a762/akm(src)
		new /obj/item/device/radio/russia(src)
		new /obj/item/device/flashlight/flare(src)
		new /obj/item/device/flashlight/flare(src)
		new /obj/item/weapon/grenade/explosive/f1(src)
		////new /obj/item/clothing/mask/gas(src)

/obj/structure/closet/secure_closet/ru_medic
	name = "russian sanitar equipment"
	req_access = list(access_ru_medic)

	New()
		..()
		new /obj/item/weapon/shovel/spade/russia(src)
		new /obj/item/clothing/under/ru_uniform(src)
		new /obj/item/clothing/shoes/jackboots(src)
		new /obj/item/clothing/head/helmet/tactical/ru(src)
		new /obj/item/clothing/suit/storage/vest/heavy/ru(src)
		new /obj/item/weapon/gun/projectile/automatic/akm(src)
		new /obj/item/weapon/storage/belt/medical(src)
		new /obj/item/weapon/storage/belt/security(src)
		for(var/i = 0; i < 3; i++)
			new /obj/item/ammo_magazine/a762/akm(src)
		new /obj/item/device/radio/russia(src)
		new /obj/item/device/flashlight/flare(src)
		new /obj/item/device/flashlight/flare(src)
		new /obj/item/weapon/storage/backpack/medic(src)
		new /obj/item/weapon/storage/bag/medical_bag_nato/full(src)
		new /obj/item/weapon/storage/bag/medical_bag_nato/full(src)

		//new /obj/item/clothing/mask/gas(src)

/obj/structure/closet/secure_closet/ru_engineer
	name = "russian saper equipment"
	req_access = list(access_ru_engineer)

	New()
		..()
		new /obj/item/weapon/shovel/spade/russia(src)
		new /obj/item/clothing/under/ru_uniform(src)
		new /obj/item/clothing/shoes/jackboots(src)
		new /obj/item/clothing/head/helmet/tactical/ru(src)
		new /obj/item/clothing/suit/storage/vest/heavy/ru(src)
		new /obj/item/weapon/gun/projectile/automatic/akm(src)
		new /obj/item/weapon/storage/belt/utility/full(src)
		new /obj/item/weapon/storage/belt/security(src)
		for(var/i = 0; i < 3; i++)
			new /obj/item/ammo_magazine/a762/akm(src)
		new /obj/item/device/radio/russia(src)
		new /obj/item/device/flashlight/flare(src)
		new /obj/item/device/flashlight/flare(src)
		new /obj/item/clothing/gloves/color/yellow(src)
		new /obj/item/weapon/storage/backpack/industrial(src)
		var/obj/item/stack/material/steel/R = new(src)
		R.amount = 50
		var/obj/item/stack/material/glass/G = new(src)
		G.amount = 50
		new /obj/item/device/multitool(src)
		new /obj/item/weapon/cell/hyper(src)
		new /obj/item/weapon/cell/hyper(src)
		new /obj/item/weapon/plastique(src)
		new /obj/item/weapon/plastique(src)
		new /obj/item/clothing/head/welding(src)
		//new /obj/item/clothing/mask/gas(src)

/obj/structure/closet/secure_closet/ru_heavy_weapon
	name = "russian pulemetchik equipment"
	req_access = list(access_ru_heavy_weapon)

	New()
		..()
		new /obj/item/weapon/shovel/spade/russia(src)
		new /obj/item/clothing/under/ru_uniform(src)
		new /obj/item/clothing/shoes/jackboots(src)
		new /obj/item/clothing/head/helmet/tactical/ru(src)
		new /obj/item/clothing/suit/storage/vest/heavy/ru(src)
		new /obj/item/weapon/gun/projectile/automatic/pkm(src)
		new /obj/item/weapon/storage/belt/security(src)
		for(var/i = 0; i < 6; i++)
			new /obj/item/ammo_magazine/a762/pkm(src)
		new /obj/item/weapon/storage/backpack(src)
		new /obj/item/device/radio/russia(src)
		new /obj/item/device/flashlight/flare(src)
		new /obj/item/device/flashlight/flare(src)
		new /obj/item/weapon/grenade/explosive/f1(src)
		new /obj/item/weapon/grenade/explosive/f1(src)
		//new /obj/item/clothing/mask/gas(src)

/obj/structure/closet/secure_closet/ru_squad_leader
	name = "russian sergant equipment"
	req_access = list(access_ru_squad_leader)

	New()
		..()
		new /obj/item/weapon/shovel/spade/russia(src)
		new /obj/item/clothing/under/ru_uniform(src)
		new /obj/item/clothing/shoes/jackboots(src)
		new /obj/item/clothing/head/helmet/tactical/ru(src)
		new /obj/item/clothing/head/soft/ru_beret(src)
		new /obj/item/clothing/suit/storage/vest/heavy/ru(src)
		new /obj/item/weapon/gun/projectile/automatic/akm(src)
		new /obj/item/weapon/storage/belt/security(src)
		for(var/i = 0; i < 8; i++)
			new /obj/item/ammo_magazine/a762/akm(src)
		new /obj/item/device/radio/russia(src)
		new /obj/item/device/radio/russia(src)
		new /obj/item/device/flashlight/flare(src)
		new /obj/item/device/flashlight/flare(src)
		new /obj/item/weapon/grenade/explosive/f1(src)
		new /obj/item/weapon/grenade/explosive/f1(src)

		new /obj/item/clothing/accessory/holster(src)
		new /obj/item/weapon/gun/projectile/pistol(src)
		new /obj/item/ammo_magazine/mc9mm(src)
		new /obj/item/ammo_magazine/mc9mm(src)
		new /obj/item/weapon/storage/box/med_kit_ruforce/full(src)
		new /obj/item/weapon/paper/map(src)
		//new /obj/item/clothing/mask/gas(src)

		new /obj/item/weapon/reagent_containers/hypospray/autoinjector/survival(src)
		new /obj/item/clothing/glasses/night(src)

//NATO HERE NATO HERE NATO HERE NATO HERE

/obj/structure/closet/secure_closet/nato_soldier
	name = "NATO soldier equipment"
	req_access = list(access_nato_soldier)

	New()
		..()
		new /obj/item/weapon/shovel/spade(src)
		new /obj/item/clothing/under/nato_uniform(src)
		new /obj/item/clothing/shoes/jackboots(src)
		new /obj/item/clothing/head/helmet/tactical/nato(src)
		new /obj/item/clothing/suit/storage/vest/heavy/nato(src)
		new /obj/item/weapon/gun/projectile/automatic/m4(src)
		new /obj/item/weapon/storage/belt/security(src)
		for(var/i = 0; i < 8; i++)
			new /obj/item/ammo_magazine/a556/m4(src)
		new /obj/item/device/radio/nato(src)
		new /obj/item/device/flashlight/flare(src)
		new /obj/item/device/flashlight/flare(src)
		new /obj/item/weapon/grenade/explosive/l2a2(src)
		new /obj/item/weapon/paper/map(src)
		//new /obj/item/clothing/mask/gas(src)

/obj/structure/closet/secure_closet/nato_medic
	name = "NATO field medic equipment"
	req_access = list(access_nato_medic)

	New()
		..()
		new /obj/item/weapon/shovel/spade(src)
		new /obj/item/clothing/under/nato_uniform(src)
		new /obj/item/clothing/shoes/jackboots(src)
		new /obj/item/clothing/head/helmet/tactical/nato(src)
		new /obj/item/clothing/suit/storage/vest/heavy/nato(src)
		new /obj/item/weapon/gun/projectile/automatic/m4(src)
		//new /obj/item/weapon/storage/belt/medical(src)
		new /obj/item/weapon/storage/belt/security(src)
		for(var/i = 0; i < 6; i++)
			new /obj/item/ammo_magazine/a556/m4(src)
		new /obj/item/device/radio/nato(src)
		new /obj/item/device/flashlight/flare(src)
		new /obj/item/device/flashlight/flare(src)
		new /obj/item/weapon/storage/backpack/medic(src)
		new /obj/item/weapon/storage/bag/medical_bag_nato/full(src)
		new /obj/item/weapon/storage/bag/medical_bag_nato/full(src)
		//new /obj/item/weapon/storage/firstaid/adv(src)
		//new /obj/item/weapon/storage/firstaid/regular(src)
		//new /obj/item/weapon/storage/firstaid/combat(src)
		//new /obj/item/clothing/mask/gas(src)

/obj/structure/closet/secure_closet/nato_engineer
	name = "NATO engineer equipment"
	req_access = list(access_nato_engineer)

	New()
		..()
		new /obj/item/weapon/shovel/spade(src)
		new /obj/item/clothing/under/nato_uniform(src)
		new /obj/item/clothing/shoes/jackboots(src)
		new /obj/item/clothing/head/helmet/tactical/nato(src)
		new /obj/item/clothing/suit/storage/vest/heavy/nato(src)
		new /obj/item/weapon/gun/projectile/automatic/m4(src)
		new /obj/item/weapon/storage/belt/utility/full(src)
		new /obj/item/weapon/storage/belt/security(src)
		for(var/i = 0; i < 3; i++)
			new /obj/item/ammo_magazine/a556/m4(src)
		new /obj/item/device/radio/nato(src)
		new /obj/item/device/flashlight/flare(src)
		new /obj/item/device/flashlight/flare(src)
		new /obj/item/clothing/gloves/color/yellow(src)
		new /obj/item/weapon/storage/backpack/industrial(src)
		var/obj/item/stack/material/steel/R = new(src)
		R.amount = 50
		var/obj/item/stack/material/glass/G = new(src)
		G.amount = 50
		new /obj/item/device/multitool(src)
		new /obj/item/weapon/plastique(src)
		new /obj/item/weapon/plastique(src)
		new /obj/item/clothing/head/welding(src)
		//new /obj/item/clothing/mask/gas(src)

/obj/structure/closet/secure_closet/nato_machinegun
	name = "NATO MG specialist equipment"
	req_access = list(access_nato_heavy_weapon)

	New()
		..()
		new /obj/item/weapon/shovel/spade(src)
		new /obj/item/clothing/under/nato_uniform(src)
		new /obj/item/clothing/shoes/jackboots(src)
		new /obj/item/clothing/head/helmet/tactical/nato(src)
		new /obj/item/clothing/suit/storage/vest/heavy/nato(src)
		new /obj/item/weapon/gun/projectile/automatic/l6_saw/m240(src)
		new /obj/item/weapon/storage/belt/security(src)
		for(var/i = 0; i < 6; i++)
			new /obj/item/ammo_magazine/a762/m240(src)
		new /obj/item/weapon/storage/backpack(src)
		new /obj/item/device/radio/nato(src)
		new /obj/item/device/flashlight/flare(src)
		new /obj/item/device/flashlight/flare(src)
		new /obj/item/weapon/grenade/explosive/l2a2(src)
		new /obj/item/weapon/grenade/explosive/l2a2(src)
		//new /obj/item/clothing/mask/gas(src)

/obj/structure/closet/secure_closet/nato_grenade_launcher
	name = "NATO GL specialist equipment"
	req_access = list(access_nato_heavy_weapon)

	New()
		..()
		new /obj/item/weapon/shovel/spade(src)
		new /obj/item/clothing/under/nato_uniform(src)
		new /obj/item/clothing/shoes/jackboots(src)
		new /obj/item/clothing/head/helmet/tactical/nato(src)
		new /obj/item/clothing/suit/storage/vest/heavy/nato(src)
		new /obj/item/weapon/gun/projectile/grenade(src)
		for(var/i = 0; i < 4; i++)
			new /obj/item/weapon/storage/box/he_grenades(src)
			new /obj/item/weapon/storage/box/smoke_grenades(src)
			//new /obj/item/weapon/storage/box/tear_grenades(src)

		new /obj/item/weapon/storage/belt/security(src)
		new /obj/item/weapon/storage/backpack(src)
		new /obj/item/device/radio/nato(src)
		new /obj/item/device/flashlight/flare(src)
		new /obj/item/device/flashlight/flare(src)
		new /obj/item/clothing/accessory/holster(src)
		new /obj/item/weapon/gun/projectile/colt(src)
		new /obj/item/ammo_magazine/c45m(src)
		new /obj/item/ammo_magazine/c45m(src)
		//new /obj/item/clothing/mask/gas(src)

/obj/structure/closet/secure_closet/nato_squad_leader
	name = "NATO squad leader equipment"
	req_access = list(access_nato_squad_leader)

	New()
		..()
		new /obj/item/weapon/shovel/spade(src)
		new /obj/item/clothing/under/nato_uniform(src)
		new /obj/item/clothing/shoes/jackboots(src)
		new /obj/item/clothing/head/helmet/tactical/nato(src)
		new /obj/item/clothing/head/soft/nato_cap(src)
		new /obj/item/clothing/suit/storage/vest/heavy/nato(src)
		new /obj/item/weapon/gun/projectile/automatic/m4(src)
		new /obj/item/weapon/storage/belt/security(src)
		for(var/i = 0; i < 8; i++)
			new /obj/item/ammo_magazine/a556/m4(src)
		new /obj/item/device/radio/nato(src)
		new /obj/item/device/radio/nato(src)
		new /obj/item/device/flashlight/flare(src)
		new /obj/item/device/flashlight/flare(src)
		new /obj/item/weapon/grenade/explosive/l2a2(src)
		new /obj/item/weapon/grenade/explosive/l2a2(src)

		new /obj/item/clothing/accessory/holster(src)
		new /obj/item/weapon/gun/projectile/colt(src)
		new /obj/item/ammo_magazine/c45m(src)
		new /obj/item/ammo_magazine/c45m(src)
		//new /obj/item/clothing/mask/gas(src)
		//new /obj/item/weapon/reagent_containers/hypospray/autoinjector/survival(src)
		new /obj/item/clothing/glasses/night(src)
		new /obj/item/weapon/paper/map(src)