#define MAP_TOWER "TOWER"
#define MAP_CITY "CITY"
#define MAP_FOREST "FOREST"
#define MAP_PILLAR "PILLAR"
#define MAP_LANDING "LANDING"
#define MAP_CAMP "CAMP"
#define MAP_REICHSTAG "REICHSTAG"

#define MODE_WAR 1
#define MODE_GERMAN_OCCUPATION 2
#define MODE_SOVIET_OCCUPATION 3