/mob/living/maim()
	Weaken(5)
	adjustBruteLoss(50)
	for (var/obj/item/organ/external/arm/arm in contents)
		if (prob(25))
			arm.droplimb()
	for (var/obj/item/organ/external/leg/leg in contents)
		if (prob(25))
			leg.droplimb()