// attempt to standardize accuracy - Kachnov
#define DEFAULT_PTRD_ACCURACY -5
#define DEFAULT_PTRD_SCOPED_ACCURACY -4

#define DEFAULT_MG_ACCURACY 0
#define DEFAULT_MG_SCOPED_ACCURACY 1

#define DEFAULT_SEMIAUTO_ACCURACY 1
#define DEFAULT_SEMIAUTO_SCOPED_ACCURACY 2

#define DEFAULT_PISTOL_ACCURACY 1
#define DEFAULT_PISTOL_SCOPED_ACCURACY 2

#define DEFAULT_BOLTACTION_ACCURACY 2
#define DEFAULT_BOLTACTION_SCOPED_ACCURACY 3






