 // attempt to standardize accuracy - Kachnov
#define DEFAULT_MG_ACCURACY -4
#define DEFAULT_PISTOL_ACCURACY 0
#define DEFAULT_BOLTACTION_ACCURACY 1
#define DEFAULT_SEMIAUTO_ACCURACY -1
#define DEFAULT_BOLTACTION_SCOPED_ACCURACY 3